// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import BoardPreviewController from "./board_preview_controller"
application.register("board-preview", BoardPreviewController)

import TrainingController from "./training_controller"
application.register("training", TrainingController)
