services:
  db:
    image: postgres:16
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build: .
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    expose:
      - "8000"
    depends_on:
      - db
    command: sh -c "PYTHONPATH=/app alembic -c backend/app/migrations/alembic.ini upgrade head && uvicorn backend.app.app:app --host=0.0.0.0 --port=8000 --reload"

  nginx:
    image: nginx:1.27
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./letsencrypt:/etc/nginx/certs:ro
      - ./htmlcov:/app/htmlcov:ro

  erd:
    build:
      context: ./schemacrawler
    image: schemacrawler/schemacrawler:latest
    depends_on:
      - db
    volumes:
      - ./backend/app/docs:/out
    environment:
      DB_TYPE: PostgreSQL
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
    command: >
      /opt/schemacrawler/bin/schemacrawler.sh
      --server=postgresql --host "$DB_HOST" --port "$DB_PORT" --database "$DB_NAME"
      --user "$DB_USER" --password "$DB_PASSWORD"
      --databaseType "PostgreSQL"
      --schemas "$DB_SCHEMA"
      --command=schema
      --output-file "/out/schema.svg"
      --info-level=STANDARD
      --log-level=INFO

volumes:
  pgdata:
