// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import BoardPreviewController from "./board_preview_controller"
application.register("board-preview", BoardPreviewController)

import OpeningThumbController from "./opening_thumb_controller"
application.register("opening-thumb", OpeningThumbController)

import TrainingController from "./training_controller"
application.register("training", TrainingController)

import PuzzleController from "./puzzle_controller"
application.register("puzzle", PuzzleController)

import PuzzleThemeBoardController from "./puzzle_theme_board_controller"
application.register("puzzle-theme-board", PuzzleThemeBoardController)

import NeedsWorkController from "./needs_work_controller"
application.register("needs-work", NeedsWorkController)

import ThemeToggleController from "./theme_toggle_controller"
application.register("theme-toggle", ThemeToggleController)

import ThemeSelectController from "./theme_select_controller"
application.register("theme-select", ThemeSelectController)

import StatTabsController from "./stat_tabs_controller"
application.register("stat-tabs", StatTabsController)

import SnowController from "./snow_controller"
application.register("snow", SnowController)
