# Revision ID: '8fca06b3d0ad'
# Revises: '0001'
# Create Date: 2026-07-06 23:56:07.949766

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fca06b3d0ad'
down_revision = '0001'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('training_responses_item_id_key'), 'training_responses', type_='unique')
    op.drop_index(op.f('ix_training_responses_item_id'), table_name='training_responses')
    op.create_index(op.f('ix_training_responses_item_id'), 'training_responses', ['item_id'], unique=True)
    op.alter_column('training_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_training_responses_item_id'), table_name='training_responses')
    op.create_index(op.f('ix_training_responses_item_id'), 'training_responses', ['item_id'], unique=False)
    op.create_unique_constraint(op.f('training_responses_item_id_key'), 'training_responses', ['item_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('training_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
